apiVersion: apps/v1
kind: Deployment
metadata:
  name: aggregator
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aggregator
  template:
    metadata:
      labels:
        app: aggregator
    spec:
      serviceAccountName: aggregator-sa
      containers:
      - name: aggregator
        image: localhost:5000/aggregator
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: aggregator
  namespace: kube-system
spec:
  selector:
    app: aggregator
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aggregator-sa
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: aggregator-role
rules:
- apiGroups: [""]
  resources: ["pods", "nodes", "persistentvolumes", "namespaces"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: aggregator-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: aggregator-role
subjects:
- kind: ServiceAccount
  name: aggregator-sa
  namespace: kube-system
