apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: cost-collector
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: cost-collector
  template:
    metadata:
      labels:
        app: cost-collector
    spec:
      serviceAccountName: cost-collector-sa
      automountServiceAccountToken: true   # automatically mount token + CA
      hostNetwork: true                     # needed for 127.0.0.1 kubelet access
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: collector
        image: localhost:5000/collector
        imagePullPolicy: Always
        env:
        - name: PUSH_ENDPOINT
          value: "http://aggregator.kube-system.svc.cluster.local:8888/metrics"
        - name: SCRAPE_INTERVAL
          value: "30"
        - name: KUBELET_ENDPOINT
          value: "https://127.0.0.1:10250/stats/summary"
        - name: DEBUG_K8S_API
          value: "false"  # Set to "true" to enable detailed HTTP logging
        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"
          limits:
            cpu: "200m"
            memory: "128Mi"
      tolerations:
      - operator: "Exists"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cost-collector-sa
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cost-collector-role
rules:
- apiGroups: [""]
  resources: ["nodes/stats", "nodes/proxy"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cost-collector-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cost-collector-role
subjects:
- kind: ServiceAccount
  name: cost-collector-sa
  namespace: kube-system
